openapi: 3.0.1
servers:
  - url: 'https://3e0dh1owv6.execute-api.us-east-1.amazonaws.com/dev'
info:
  title: Prepaid
  description: Prepaid POC
  version: 1.0.0
tags:
  - name: cards
    description: Cards
  - name: transactions
    description: Transactions
paths:
  /card/new:
    post:
      tags:
        - cards
      summary: Create a new card
      operationId: card-new
      parameters:
        - name: amt
          in: query
          description: Initial amount
          required: false
          schema:
            type: number
            format: float
      security:
        - auth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/CardStatus'
        '500':
          description: Invalid input
  /card/{id}/status:
    post:
      tags:
        - cards
      summary: Get status of a card
      operationId: card-status
      parameters:
        - name: id
          in: path
          description: Card ID
          required: true
          schema:
            type: string
      security:
        - auth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/CardStatus'
        '500':
          description: Invalid input
  /card/{id}/topup:
    post:
      tags:
        - cards
      summary: Top up card
      operationId: card-topup
      parameters:
        - name: id
          in: path
          description: Card ID
          required: true
          schema:
            type: string
        - name: amt
          in: query
          description: Amount to top up
          required: true
          schema:
            type: number
            format: float
      security:
        - auth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/CardStatus'
        '500':
          description: Invalid input
  /card/{id}/spend:
    post:
      tags:
        - cards
        - transactions
      summary: Authorization request to spend money oncard
      operationId: card-spend
      parameters:
        - name: id
          in: path
          description: Card ID
          required: true
          schema:
            type: string
        - name: amt
          in: query
          description: Amount to authorize to spend
          required: true
          schema:
            type: number
            format: float
        - name: merchant
          in: query
          description: Name of merchant
          required: true
          schema:
            type: string
      security:
        - auth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/TxStatus'
        '500':
          description: Invalid input
  /card/{id}/statement:
    get:
      tags:
        - cards
        - transactions
      summary: Get statement of a card
      operationId: card-statement
      parameters:
        - name: id
          in: path
          description: Card ID
          required: true
          schema:
            type: string
      security:
        - auth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/CardStatement'
        '500':
          description: Invalid input
  /tx/{id}/status:
    post:
      tags:
        - transactions
      summary: Get status of a transaction
      operationId: tx-status
      parameters:
        - name: id
          in: path
          description: Transaction ID
          required: true
          schema:
            type: string
      security:
        - auth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/TxStatus'
        '500':
          description: Invalid input
  /tx/{id}/reverse:
    post:
      tags:
        - transactions
      summary: Reverse part of transaction for amount
      operationId: tx-reverse
      parameters:
        - name: id
          in: path
          description: Transaction ID
          required: true
          schema:
            type: string
        - name: amt
          in: query
          description: Amount to reverse
          required: true
          schema:
            type: number
            format: float
      security:
        - auth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/TxStatus'
        '500':
          description: Invalid input
  /tx/{id}/capture:
    post:
      tags:
        - transactions
      summary: Capture part of transaction for amount
      operationId: tx-capture
      parameters:
        - name: id
          in: path
          description: Transaction ID
          required: true
          schema:
            type: string
        - name: amt
          in: query
          description: Amount to capture
          required: true
          schema:
            type: number
            format: float
      security:
        - auth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/TxStatus'
        '500':
          description: Invalid input
  /tx/{id}/refund:
    post:
      tags:
        - transactions
      summary: Refund part of transaction for amount
      operationId: tx-refund
      parameters:
        - name: id
          in: path
          description: Transaction ID
          required: true
          schema:
            type: string
        - name: amt
          in: query
          description: Amount to refund
          required: true
          schema:
            type: number
            format: float
      security:
        - auth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/TxStatus'
        '500':
          description: Invalid input
components:
  securitySchemes:
    auth:
      type: apiKey
      description: API key authentication
      name: x-api-key
      in: header
  schemas:
    CardStatus:
      type: object
      properties:
        id:
          type: string
        balance:
          type: number
          format: float
        blocked:
          type: number
          format: float
    TxStatus:
      type: object
      properties:
        id:
          type: string
        blocked:
          type: number
          format: float
        captured:
          type: number
          format: float
        refunded:
          type: number
          format: float
        expires:
          type: string
    CardStatement:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/CardStatement'
        tx:
          type: array
          items:
            $ref: '#/components/schemas/TxStatus'
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
